version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true

image:
- Visual Studio 2022

configuration:
- Debug
- Mixed
- Release
- Release Master Gold

platform:
- x64
- x86

branches:
  except:
    - dependabot/*

cache:
- src/packages -> **/packages.config

test: off

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: OpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: kGVniXDR926BfVcA97y25BzALbijvgboBsozZzY9yc8RPz15Q4YG474h7vl14/J1
  artifact:
    OpenXRay.*.7z, Symbols.*.7z, Utils.*.7z
  draft: true
  force_update: true
